version: "3.7"

services:
  xphp:
    environment:
      - "XDEBUG_SESSION=PHPSTORM"
      - "XDEBUG_CONFIG=client_host=host.docker.internal"
      - "PHP_IDE_CONFIG=serverName=CLI"
    networks:
      - default # necessary for XDEBUG

networks:
  default:
    external:
      name: webgateway
